# Generated by Django 3.2.5 on 2021-07-17 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20210717_1952'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookInstances',
            new_name='BookInstance',
        ),
    ]
